### ISSUE TITLE
Provide releases on Drupal.org?

### ISSUE THREAD

**Issue by JPustkuchen** [chapter-three/simple_amp#1]
Hi and thank you very very much for this great module.

Would it be possible to at least push important tags to Drupal.org als module project? I think there are still many people looking for modules at DO.

Thank you very much.

**Comment by minnur** [comment]
Yes, the goal is to release this on drupal.org

**Comment by minnur** [comment]
@JPustkuchen the module has been released on Drupal.org https://www.drupal.org/project/simple_amp
